PATCH http://localhost:3001/api/auth/update-password
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5Y2ZkMzBhMTYxOTUyOGQ4NDU2OWMyMyIsImlhdCI6MTc3NTIzMDA4MiwiZXhwIjoxNzc1MjMwOTgyfQ.48Y2zRxnN193ljIPgTPy6k-g06KcTvKav_Oux961lU8
{
    "oldPassword": "Markdoe12343#",
    "newPassword": "Markdoe123453#",
    "confirmPassword": "Markdoe123453#"
}
